Fix retrieving template.html location
Now that NQP and Rakudo are relocatable we must not rely on a build time
path. NQP home is meant to always point to the actual runtime path.
For this purpose introduce the home-dir() method on the Compiler object
which will determine the current NQP home directory at runtime. This is
analogous to a feature Rakudo also has (Rakudo home).

On JVM the necessary vm command line argument needed to enable the VM to
know the scripts executable path was not set. Do so now.

diff --git a/tools/templates/jvm/nqp-j.in b/tools/templates/jvm/nqp-j.in
--- a/tools/templates/jvm/nqp-j.in
+++ b/tools/templates/jvm/nqp-j.in
@@ -1,10 +1,35 @@
 @shebang@
 
-@if(platform==windows
-@setenv(JAR_DIR)@@jar_dir@
-@setenv(LIB_DIR)@@lib_dir@)@
-@if(platform!=windows
-@setenv(JAR_DIR)@@q(@jar_dir@)@
-@setenv(LIB_DIR)@@q(@lib_dir@)@)@
+# Sourced from https://stackoverflow.com/a/29835459/1975049
+rreadlink() (
+  target=$1 fname= targetDir= CDPATH=
+  { \unalias command; \unset -f command; } >/dev/null 2>&1
+  [ -n "$ZSH_VERSION" ] && options[POSIX_BUILTINS]=on
+  while :; do
+      [ -L "$target" ] || [ -e "$target" ] || { command printf '%s\n' "ERROR: '$target' does not exist." >&2; return 1; }
+      command cd "$(command dirname -- "$target")"
+      fname=$(command basename -- "$target")
+      [ "$fname" = '/' ] && fname=''
+      if [ -L "$fname" ]; then
+        target=$(command ls -l "$fname")
+        target=${target#* -> }
+        continue
+      fi
+      break
+  done
+  targetDir=$(command pwd -P)
+  if [ "$fname" = '.' ]; then
+    command printf '%s\n' "${targetDir%/}"
+  elif  [ "$fname" = '..' ]; then
+    command printf '%s\n' "$(command dirname -- "${targetDir}")"
+  else
+    command printf '%s\n' "${targetDir%/}/$fname"
+  fi
+)
 
-@exec(java)@ -Xss1m -Xmx1324m -Xbootclasspath/a:"@cur_dir@@envvar(LIB_DIR)@@cpsep@@nfp(@envvar(JAR_DIR)@/nqp-runtime.jar)@@cpsep@@nfp(@envvar(JAR_DIR)@/@asmfile@)@@cpsep@@nfp(@envvar(JAR_DIR)@/@jlinefile@)@@cpsep@@nfp(@envvar(JAR_DIR)@/@jnafile@)@@cpsep@@nfp(@envvar(LIB_DIR)@/nqp.jar)@" -cp "@cur_dir@@envvar(LIB_DIR)@" nqp @sh_allparams@
+EXEC=$(rreadlink "$0")
+DIR=$(dirname -- "$EXEC")
+@setenv(JAR_DIR)@@q(@jar_dir@)@
+@setenv(LIB_DIR)@@q(@lib_dir@)@
+
+@exec(java)@ -Dnqp.execname="$EXEC" -Xss1m -Xmx1324m -Xbootclasspath/a:"@cur_dir@@envvar(LIB_DIR)@@cpsep@@nfp(@envvar(JAR_DIR)@/nqp-runtime.jar)@@cpsep@@nfp(@envvar(JAR_DIR)@/@asmfile@)@@cpsep@@nfp(@envvar(JAR_DIR)@/@jlinefile@)@@cpsep@@nfp(@envvar(JAR_DIR)@/@jnafile@)@@cpsep@@nfp(@envvar(LIB_DIR)@/nqp.jar)@" -cp "@cur_dir@@envvar(LIB_DIR)@" nqp @sh_allparams@
